package com.nkd.nexbridge.routing;

public enum ConditionOperator {
    EQUALS, NOT_EQUALS, CONTAINS, NOT_CONTAINS, STARTS_WITH, ENDS_WITH,
    GREATER_THAN, LESS_THAN, GREATER_THAN_OR_EQUAL, LESS_THAN_OR_EQUAL,
    IS_NULL, IS_NOT_NULL, MATCHES_REGEX
}
